### PR TITLE
fix: update @apollo/client import paradigm

### PR DESCRIPTION
**Pull request by FoodProduct**
Depends on https://github.com/apollographql/apollo-client/pull/7645.

Some of these imports are doable today; some are not exposed by Apollo Client via cjs yet.

Also, `npm run format` had some misc changes...

### CODE REVIEW

**Review by danReynolds — APPROVED** [review]

**Comment by danReynolds** [comment]
Lgtm assuming we get everything exposed

**Comment by FoodProduct** [comment]
Waiting until Apollo Client v3.4 is released, which will include the PR mentioned in the description.

**Comment by danReynolds** [comment]
@FoodProduct Apollo 3.4 is released, should we pick this back up?

**Comment by FoodProduct** [comment]
> @FoodProduct Apollo 3.4 is released, should we pick this back up?

Yes, ideally!

**Comment by FoodProduct** [comment]
Closing because I don't see my self doing this any time soon 🙃

**Pull request closed without merging**
